[package]
name = "actix-hello"
version = "0.1.0"
edition = "2021"
[dependencies]
actix-files = "0.6.2"
actix-web = "4"
env_logger = "0.9.3"
log = "0.4"
serde = "1.0.145"
serde_derive = "1.0.145"
toml = "0.5"
